name: Node CI

on:
    push:
    pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x]
        # TODO : add windows as target
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
